name: 'Chromatic'

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3

      - name: Install dependencies
        run: |
          pnpm i
          pnpm nuxi prepare

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true
          #autoAcceptChanges: 'main'
