name: 'Chromatic'

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Use pnmp
        uses: pnpm/action-setup@v3

      - name: Install dependencies
        run: |
          pnpm install
          pnpm nuxi prepare

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true
          #autoAcceptChanges: 'main'
